name: Run Merge Script

on:
  workflow_dispatch:
  # run after layout verification
  workflow_run:
    workflows: ["Run Layout Verification"]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout SiEPIC siepic_ebeam_pdk
          python -m pip install --upgrade SiEPIC

      - name: run merge script
        run: |

          python merge/EBeam_merge.py

      - name: commit outputted files into repository
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

          output_files="EBeam.gds EBeam.oas EBeam.txt EBeam.coords"

          IFS=' '

          for file in $output_files; do
            git add "merge/$file"
            echo "git add $file"
          done

          git commit -m "add merge script output file to merge/"
          git push