name: Run Merge Script

on:
  workflow_dispatch:
  # run after layout verification
  workflow_run:
    workflows: ["Run Layout Verification"]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout SiEPIC siepic_ebeam_pdk
          python -m pip install --upgrade SiEPIC

      - name: run merge script
        run: |

          python merge/EBeam_merge.py

      - name: move merge output files to new folder
        run: |
          #output_files="EBeam.gds EBeam.oas EBeam.txt EBeam.coords"
          output_files="EBeam.oas EBeam.txt"

          IFS=' '

          mkdir -p merge_output

          for file in $output_files; do
            cp "/home/runner/work/openEBL-2024-02/openEBL-2024-02/merge/$file" merge_output/
          done

      - name: upload artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: merge-files
          path: merge_output/

      - name: echo artifact id and run id
        run: |
          echo 'Artifact ID is ${{ steps.artifact-upload.outputs.artifact-id }}'
          echo 'Run ID is ${{ github.run_id }}'

      - name: get artifact url
        run: |
          IFS='/' read -ra REPO <<< "$GITHUB_REPOSITORY"
          OWNER="${REPO[0]}"
          REPO_NAME="${REPO[1]}"
          echo "Owner: $OWNER"
          echo "Repository: $REPO_NAME"

          RUN_ID=${{ github.run_id }}
          ARTIFACT_ID=${{ steps.artifact-upload.outputs.artifact-id }}

          ARTIFACT_URL="https://github.com/$OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts/$ARTIFACT_ID"

          echo "Artifact URL: $ARTIFACT_URL"

          echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV

          if [ $OWNER == "SiEPIC" ];then
            echo 'SiEPIC'
          
          fi
        
      - name: update url in readme
        uses: theboi/github-update-readme@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          footer: "Footer [artifact url]($ARTIFACT_URL)"


            
