name: Run Python Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      PYTHON_SCRIPT_PATH: '"submissions/Klayout Python"'

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout SiEPIC siepic_ebeam_pdk
          python -m pip install --upgrade SiEPIC

      - name: Debug information
        run: |
          ls -R submissions
          ls -R ${PYTHON_SCRIPT_PATH}

      - name: get python scripts from submissions / Klayout Python/**.py'
        run: |

          export FILES=$(find ${PYTHON_SCRIPT_PATH} -type f -name "*.py")
          echo "FILES=$FILES" >> $GITHUB_ENV

          echo "Added / modified Python files; $FILES"

          IFS=$'\n'
        
          # run all python files to get gds/oas output
          for file in $FILES; do

            echo "Getting gds/oas output for $file"

            python $file 

            echo "Done for $file"

          done
        working-directory: ${{ github.workspace }}

      - name: get oas file names
        run: |
          export OAS_FILES=()
          for file in $FILES; do
            oas_file="${file%.py}.oas"
            OAS_FILES+=("$oas_file")
          done

          echo "oas files: $oas_files"

          echo "OAS_FILES=$OAS_FILES" >> $GITHUB_ENV

      - name: commit outputted gds/oas files into repository
        run: |
          git config --local user.email jasminabrar@users.noreply.github.com
          git config --local user.name "jasminabrar"
          
          # git add all produced oas files
          for file in $OAS_FILES; do
            git add "$file"
          done

          git commit -m "Add oas files produced from .py files"      
          git push    



